# Generated by Django 4.1.1 on 2022-09-14 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('location', models.CharField(max_length=255, verbose_name='Company Headquarter')),
                ('website', models.URLField(blank=True, null=True)),
                ('company_email', models.EmailField(max_length=100, verbose_name='Company Email')),
                ('company_logo', models.ImageField(upload_to='company', verbose_name='Company Logo')),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('catgory', models.CharField(max_length=100, verbose_name='Job Category')),
                ('job_type', models.CharField(max_length=200, verbose_name='Job Type')),
                ('region', models.CharField(default='world wide', max_length=255, verbose_name='Job Region')),
                ('job_zone', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=100, verbose_name='Expected Salary')),
                ('application', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
                ('skills', models.ManyToManyField(to='jobs.jobskill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
