# Generated by Django 4.1.1 on 2022-09-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_zone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
