# Generated by Django 4.1.1 on 2022-09-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_catgory_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.jobskill'),
            preserve_default=False,
        ),
    ]
