# Generated by Django 4.1.1 on 2022-09-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_skills_job_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(default='this is a test description'),
        ),
    ]
