# Generated by Django 3.2.2 on 2022-09-23 14:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='jobs.JobSkill'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('applicant_name', models.CharField(max_length=250, verbose_name='Names')),
                ('email', models.EmailField(max_length=200)),
                ('resume', models.FileField(upload_to='jobs')),
                ('github_link', models.URLField()),
                ('portfolio_link', models.URLField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
